### ISSUE TITLE
quotec能正常调用，而quote_detail会报错

### ISSUE THREAD

**Issue by linzehui** [uname-yang/pysnowball#22]
如题，请问 这是因为token的问题吗
```
>>> ball.quotec("SH600104")
{'data': [{'symbol': 'SH600104', 'current': 16.34, 'percent': -1.51, 'chg': -0.25, 'timestamp': 1651820400000, 'volume': 34602480, 'amount': 562988432.35, 'market_capital': 190907758704.0, 'float_market_capital': 190907758704.0, 'turnover_rate': 0.3, 'amplitude': 1.45, 'open': 16.3, 'last_close': 16.59, 'high': 16.4, 'low': 16.16, 'avg_price': 16.270175789423188, 'trade_volume': None, 'side': None, 'is_trade': False, 'level': 2, 'trade_session': None, 'trade_type': None, 'current_year_percent': -20.79, 'trade_unique_id': None, 'type': 11, 'bid_appl_seq_num': None, 'offer_appl_seq_num': None, 'volume_ext': None, 'traded_amount_ext': None, 'trade_type_v2': None}], 'error_code': 0, 'error_description': None}
>>> ball.quote_detail("SH600104")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xx/anaconda3/lib/python3.9/site-packages/pysnowball/realtime.py", line 14, in quote_detail
    return utls.fetch(api_ref.realtime_quote_detail+symbol)
  File "/Users/xx/anaconda3/lib/python3.9/site-packages/pysnowball/utls.py", line 25, in fetch
    raise Exception(response.content)
Exception: b'{"error_description":"\xe9\x81\x87\xe5\x88\xb0\xe9\x94\x99\xe8\xaf\xaf\xef\xbc\x8c\xe8\xaf\xb7\xe5\x88\xb7\xe6\x96\xb0\xe9\xa1\xb5\xe9\x9d\xa2\xe6\x88\x96\xe8\x80\x85\xe9\x87\x8d\xe6\x96\xb0\xe7\x99\xbb\xe5\xbd\x95\xe5\xb8\x90\xe5\x8f\xb7\xe5\x90\x8e\xe5\x86\x8d\xe8\xaf\x95","error_uri":"/v5/stock/quote.json","error_data":null,"error_code":"400016"}'
```

**Comment by uname-yang** [comment]
是
